# ALIASES START

zeroTrue: &zeroTrue
  score: 0
  countWords: true

zeroFalse: &zeroFalse
  score: 0
  countWords: false

headingDefaults: &headingDefaults
  score: 1
  countWords: true

boostedFalse: &boostedFalse
  score: 5
  countWords: false

boostedTrue: &boostedTrue
  score: 5
  countWords: true

tcrHtmlConfig: &tcrHtmlConfig
  a: *boostedTrue
  code: *boostedFalse
  img: *boostedFalse
  h1: *headingDefaults
  h2: *headingDefaults
  h3: *headingDefaults
  h4: *headingDefaults
  h5: *headingDefaults
  h6: *headingDefaults
  br: *zeroTrue
  p: *zeroTrue
  em: *zeroTrue
  ul: *zeroTrue
  td: *zeroTrue
  hr: *zeroTrue
  ol: *zeroTrue
  pre: *zeroFalse
  strong: *zeroFalse
  blockquote: *zeroFalse
  li:
    score: 0.1
    countWords: true

allRoles: &allRoles
  - collaborator
  - contributor

collaboratorOnly: &collaboratorOnly
  - collaborator

teamMembersOnly: &teamMembersOnly
  - COLLABORATOR
  - OWNER
  - MEMBER
  - ADMIN

timeLabels: &timeLabels
  - name: "Time: <15 Minutes"
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"

priorityLabels: &priorityLabels
  - name: "Priority: 0 (Regression)"
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"

# ALIASES END

plugins:
  - uses:
      - plugin: https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev
        skipBotEvents: false
        with:
          reviewDelayTolerance: 3 Days
          taskStaleTimeoutDuration: 30 Days
          startRequiresWallet: true
          maxConcurrentTasks:
            collaborator: 2
            contributor: 2
          emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
          rolesWithReviewAuthority: *teamMembersOnly
          requiredLabelsToStart:
            - name: "Priority: 0 (Regression)"
              allowedRoles: *allRoles
            - name: "Priority: 1 (Normal)"
              allowedRoles: *allRoles
            - name: "Priority: 2 (Medium)"
              allowedRoles: *allRoles
            - name: "Priority: 3 (High)"
              allowedRoles: *collaboratorOnly
            - name: "Priority: 4 (Urgent)"
              allowedRoles: *collaboratorOnly
            - name: "Priority: 5 (Emergency)"
              allowedRoles: *collaboratorOnly

  - uses:
      - plugin: https://ubiquity-os-command-wallet-main.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false

  - uses:
      - plugin: ubiquity-os-marketplace/command-ask@main
        with:
          model: anthropic/claude-3.5-sonnet
          openAiBaseUrl: https://openrouter.ai/api/v1

  - uses:
      - plugin: https://ubiquity-os-command-query-user-main.ubiquity.workers.dev
        with:
          allowPublicQuery: true

  - uses:
      - plugin: https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev
        with:
          labels:
            time: *timeLabels
            priority: *priorityLabels
          basePriceMultiplier: 2
          publicAccessControl:
            setLabel: true
            fundExternalClosedIssue: false

  - skipBotEvents: false
    uses:
      - plugin: ubiquity-os-marketplace/text-conversation-rewards@main
        with:
          logLevel: debug
          evmNetworkId: 100
          evmPrivateEncrypted: bd5AFnSCO6c5jJyPifpOfr5Zys29RE7SyXkEU3akT13RtGmYDrqGIGuvJQyH53HA5dIba7PL5bXfll0JebmwXYe5gHIXSGX80WuGMDHh0cFfeGjHhmUXe8kkZ1OT2De9qRpqejJcEzdfi-8XNAvP7cQu2Vt-7RNnPw
          incentives:
            contentEvaluator:
              enabled: true
            userExtractor:
              enabled: true
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              multipliers:
                - role:
                    - ISSUE_SPECIFICATION
                    - ISSUE_AUTHOR
                    - ISSUE_COLLABORATOR
                    - PULL_COLLABORATOR
                    - PULL_SPECIFICATION
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                    html: *tcrHtmlConfig
                - role:
                    - ISSUE_CONTRIBUTOR
                    - ISSUE_ASSIGNEE
                  multiplier: 0.25
                  rewards:
                    wordValue: 0.1
                    html: *tcrHtmlConfig
                - role:
                    - PULL_AUTHOR
                    - PULL_CONTRIBUTOR
                    - PULL_ASSIGNEE
                  multiplier: 0
                  rewards:
                    wordValue: 0
                    html: *tcrHtmlConfig
            permitGeneration: {}
            reviewIncentivizer: {}
            githubComment:
              post: true
              debug: false

  - skipBotEvents: false
    uses:
      - plugin: ubiquity-os-marketplace/daemon-disqualifier@main
        skipBotEvents: false
        with:
          warning: 7 days
          pullRequestRequired: true
          eventWhitelist:
            - pull_request.review_requested
            - pull_request.ready_for_review
            - pull_request_review_comment.created
            - issue_comment.created
            - push
          disqualification: 14 days

  - uses:
      - plugin: ubiquity-os-marketplace/daemon-merging@main
        with:
          approvalsRequired:
            collaborator: 1
            contributor: 2
          mergeTimeout:
            collaborator: 3.5 days
            contributor: 7 days
          allowedReviewerRoles:
            - COLLABORATOR
            - MEMBER
            - OWNER

  - uses:
      - plugin: ubiquity-os-marketplace/text-vector-embeddings@main
        with:
          matchThreshold: 0.95
          warningThreshold: 0.75
          jobMatchingThreshold: 0.75

  - uses:
      - plugin: ubiquity-os-marketplace/daemon-pull-review@main
